### ISSUE TITLE
Write templatized Solve Linear that can use a fraction class or floating points

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#119]

**Comment by cameroncuster** [comment]
If we templatize this, then we should also templatize mod_exp and n_choose_k

**Comment by lrvideckis** [comment]
Also every other place which uses a `mod`

**Comment by lrvideckis** [comment]
my preference: let's keep the mods. reason: it's easier to remove code than add; code is more customized

**Comment by lrvideckis** [comment]
I'd be okay with templatizing if we also add a golfed mod-int

**Comment by cameroncuster** [comment]
Do we want it to be golfed, or like overflow safe? (they aren't necessarily the same thing)

**Comment by cameroncuster** [comment]
Like we could just golf the AtCoder one, if this is what you're thinking?

**Comment by lrvideckis** [comment]
keeping mods means no overflow, so less overall code. (also it's overflow safe)

**Comment by lrvideckis** [comment]
I was thinking start with kactl's - it's already much closer to what we want
