### ISSUE TITLE
Add Bitmask Hackpack Code

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#127]
- Iterating over all submaks and supermaks O(3^n)
- Iterating over all bitmasks of size N with exactly K bits set

**Comment by lrvideckis** [comment]
submasks - https://codeforces.com/blog/entry/45930?#comment-304251
subsets with k bits - https://codeforces.com/blog/entry/82379?#comment-711091 (let's choose some implementation we like

**Comment by lrvideckis** [comment]
Maybe add a test comparing num iterations of k-subset to n choose k

**Comment by lrvideckis** [comment]
let's add these problems as tests:
https://onlinejudge.u-aizu.ac.jp/courses/lesson/8/ITP2/all/ITP2_11_D
https://onlinejudge.u-aizu.ac.jp/courses/lesson/8/ITP2/all/ITP2_11_C

**Comment by lrvideckis** [comment]
This problem may be more useful for testing submasks/supermasks

https://onlinejudge.u-aizu.ac.jp/courses/lesson/8/ITP2/all/ITP2_11_B
