### ISSUE TITLE
Add Tree Isomorphism Code

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#139]
[Tree Hashing]
https://open.kattis.com/problems/treequivalence
https://cses.fi/problemset/task/1700
https://cses.fi/problemset/task/1701

**Comment by lrvideckis** [comment]
Let's separate finding a centroid from the centroid decomposition code. Then make tree isomorphism depend on centroid finding

**Comment by lrvideckis** [comment]
also, for CSES, once you solve a problem, you can browse other's submissions. So we can try to find something cleaner

**Comment by lrvideckis** [comment]
Library checker just added tree isomorphism! Easy testing now

https://judge.yosupo.jp/problem/rooted_tree_isomorphism_classification
