### ISSUE TITLE
Refactor Centroid Decomp.

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#215]
Instead of erasing back edge to parent, let's just not visit it (this should work due to the underlying structure of centroid decomp.)

**Comment by lrvideckis** [comment]
So you'll add a visited array? You'll need to have add this visited array as a param in the lambda, and update both  `count_paths_per_length.h` and `count_paths_per_node.h`

**Comment by lrvideckis** [comment]
idk - I kinda liked how in the lambda, you could just treat the adj-list normally and not have to check any extra visited array

**Comment by cameroncuster** [comment]
No, you know how we do the DFS(int u, int p), we will pass the centroid in as the parent. I didn't think this would work originally, but after talking to Seba they explained that it should.

**Comment by cameroncuster** [comment]
It's the same thing, but instead of actually erasing the edge we are going to not traverse it.

**Comment by lrvideckis** [comment]
Ok I'll wait to see the implementation

**Comment by cameroncuster** [comment]
This does not work, lol
