### ISSUE TITLE
revamp documentation

### ISSUE THREAD

**Issue by lrvideckis** [lrvideckis/programming_team_code#224]
I no longer recommend we use this https://github.com/online-judge-tools/verification-helper#generating-documentation

I want the docs to be comments-only so the PDF is also documented

**Comment by lrvideckis** [comment]
another option: https://codeforces.com/blog/entry/63800, but the PDF's it generates is basically the same as what we have currently

**Comment by cameroncuster** [comment]
I'm closing this for now, because I am happy with what we currently have. Feel free to reopen if you want to dive deeper @lrvideckis .

**Comment by lrvideckis** [comment]
probs let's use doxygen

**Comment by lrvideckis** [comment]
https://doxygen.nl/manual/commands.html

**Comment by lrvideckis** [comment]
Let's follow the example comment in https://github.com/lrvideckis/programming_team_code/blob/master/library/README.md
