### ISSUE TITLE
[new alg] add sum over subsets

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#236]

**Comment by lrvideckis** [comment]
https://codeforces.com/blog/entry/45223

**Comment by lrvideckis** [comment]
this already is in kactl's pdf, should we do out of scope?

**Comment by cameroncuster** [comment]
Can you link it? @lrvideckis

**Comment by lrvideckis** [comment]
https://github.com/kth-competitive-programming/kactl/blob/648db472abd1987c159862aa5582c19082723399/content/various/chapter.tex#L32

**Comment by cameroncuster** [comment]
I was thinking all the ones referenced here https://cses.fi/problemset/task/1654

**Comment by lrvideckis** [comment]
isn't that solved with SOS DP?

**Comment by lrvideckis** [comment]
But ya, I think it's a good idea to add solutions to various CSES problems to the hackpack

**Comment by cameroncuster** [comment]
Yeah true, and hackpack-cpp has the actual solution code.

**Comment by cameroncuster** [comment]
Added link to hackpack-cpp
