### ISSUE TITLE
Lint for Lines which exceed 80 characters

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#238]

**Comment by lrvideckis** [comment]
I recommend we do 120

https://www.reddit.com/r/programming/comments/gt4wgn/linus_torvalds_on_80character_line_limit/fs9tsif

**Comment by cameroncuster** [comment]
My reasoning was because it cuts off in the PDF, alternatively we could change the PDF format.

**Comment by lrvideckis** [comment]
https://astyle.sourceforge.net/astyle.html#_max-code-length
