### ISSUE TITLE
[new alg] Multipoint Evaluation with Polynomial Division

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#244]
Insp. https://github.com/e-maxx-eng/e-maxx-eng-aux/blob/master/src/polynomial.cpp

https://cp-algorithms.com/algebra/polynomial.html

Insp. Calculate i! for i in range [0, 1e12], with a mod in the range [1, 1e18]

For testing: https://dmoj.ca/problem/factorial3

**Comment by lrvideckis** [comment]
Looks like Library checker has a "polynomial" tab with a bunch of polynomial operations

It begs the question: how much polynomial stuff do we want to add?

**Comment by lrvideckis** [comment]
Looks complicated haha
