### ISSUE TITLE
Make n_choose_k mod constant template argument

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#269]
- constant mods are way faster (TLE -> AC) on various CF problems

**Comment by lrvideckis** [comment]
Also all other places where a mod is used

**Comment by cameroncuster** [comment]
my problem is sometimes you have a variable mod, so I'm a bit torn about what to put

**Comment by cameroncuster** [comment]
If we just had a static mod int we wouldn't have to add the template

**Comment by lrvideckis** [comment]
> * constant mods are way faster (TLE -> AC) on various CF problems

Thanks for doing this benchmarking

**Comment by cameroncuster** [comment]
> > * constant mods are way faster (TLE -> AC) on various CF problems
> 
> Thanks for doing this benchmarking

So I was just TLEing on this problem, and made my mod const which was AC (https://codeforces.com/contest/1616/submission/173015296)

**Comment by lrvideckis** [comment]
If we don't use `ac-library`'s modint, then let's revert this: https://github.com/lrvideckis/programming_team_code/commit/277ce19021f6fdab4a6ab8be1dbba75fdee9442d
