### ISSUE TITLE
[new alg] Min25 Sieve

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#276]
This came up in a contest: https://codeforces.com/blog/entry/92703

**Comment by lrvideckis** [comment]
looks similar to this https://cp-algorithms.com/algebra/sieve-of-eratosthenes.html#segmented-sieve

**Comment by lrvideckis** [comment]
candidate problems to test:
- https://judge.yosupo.jp/problem/counting_primes
- https://judge.yosupo.jp/problem/enumerate_primes
- https://judge.yosupo.jp/problem/sum_of_totient_function
