### ISSUE TITLE
make RMQ work for non-idempotent elements&operations (like product, number of minimums/maximums)

### ISSUE THREAD

**Issue by lrvideckis** [lrvideckis/programming_team_code#279]
https://codeforces.com/blog/entry/87940

https://github.com/sgtlaugh/algovault/blob/master/code_library/disjoint_sparse_table.cpp

another implementation idea: https://discuss.codechef.com/t/tutorial-disjoint-sparse-table/17404

**Comment by cameroncuster** [comment]
This is sick
