### ISSUE TITLE
add common node to hackpack using LCA

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/programming_team_code#291]
ref: https://github.com/nealwu/competitive-programming/blob/master/rmq_lca/rmq_lca.cc#L273

**Comment by cameroncuster** [comment]
How to test this though? (also should we add it directly to the LCA struct or do something like you did for kth node on path?) @lrvideckis

**Comment by lrvideckis** [comment]
are there any other functions from that struct that you also want to add?

**Comment by cameroncuster** [comment]
Not ATM, I like the compress tree function, but KACTL already supports that.

**Comment by cameroncuster** [comment]
Functions like Kth Ancestor are kinda helpful, not sure if they're worth adding, we have the Kth node on path which is the hardest one.

**Comment by lrvideckis** [comment]
Have you used the LCA hash code in any contest?

The main reason to split up LCA and kth_node was to keep LCA shorter for the hash code

**Comment by lrvideckis** [comment]
let's add to `lca` struct to reduce the # of files by 1
