### ISSUE TITLE
Make Hungarian take in an adjacency list

### ISSUE THREAD

**Issue by lrvideckis** [lrvideckis/programming_team_code#296]
Instead of adj matrix

**Comment by cameroncuster** [comment]
Hmm how come?

**Comment by lrvideckis** [comment]
better complexity for sparse graphs

**Comment by cameroncuster** [comment]
The time is described as O(n^2 * m), is that a result of using an adj matrix? What is the runtime using an adj list?

**Comment by cameroncuster** [comment]
Also will it be like nodes on left side have directed edges to nodes on the right side, and you give the left side in the input?

**Comment by lrvideckis** [comment]
regarding complexity, replacing matrix with list will speed up this loop:

https://github.com/lrvideckis/programming_team_code/blob/master/library/flow/hungarian.hpp#L38

**Comment by lrvideckis** [comment]
also with list, there's no longer the need to mark edge weights as `INF` to represent "edge doesn't exist"
