### ISSUE TITLE
change get_rand back to inclusive-inclusive

### ISSUE THREAD

**Issue by lrvideckis** [lrvideckis/programming_team_code#367]
this range is missing the value int-max

https://github.com/lrvideckis/programming_team_code/blob/fd41772f56e94e62b3372ee98880122aa20ecb10/tests/library_checker_aizu_tests/handmade_tests/distinct_query.test.cpp#L13

**Comment by cameroncuster** [comment]
strongly agree, it's just cleaner to go with what the STL does (they have their reasons)

**Comment by lrvideckis** [comment]
👍
