### ISSUE TITLE
consider removing matrix mul pow (it's old and crusty)

### ISSUE THREAD

**Issue by lrvideckis** [lrvideckis/programming_team_code#78]
Find a good alternative

**Comment by lrvideckis** [comment]
Ditto tree count path lengths with missing fft

**Comment by lrvideckis** [comment]
Ditto dsuTree

**Comment by lrvideckis** [comment]
Ditto persistentSegTree, but keep the lazy PST

**Comment by cameroncuster** [comment]
I used this yesterday

**Comment by lrvideckis** [comment]
Which one?

**Comment by cameroncuster** [comment]
The matrix mult pow

**Comment by lrvideckis** [comment]
moved centroid stuff to #80 and have decided to keep matrix mul pow
